# Generated by Django 5.2.8 on 2025-11-20 12:16

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Members', models.JSONField(default=list)),
                ('Admins', models.JSONField(default=list)),
                ('CanAnyonePost', models.BooleanField(default=True)),
                ('Private', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Username', models.CharField(unique=True)),
                ('Password', models.CharField()),
                ('Email', models.CharField(blank=True, null=True)),
                ('Groups', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('File', models.FileField(upload_to=main.models.upload_path)),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main.groups')),
            ],
        ),
    ]
