# Generated by Django 5.2.8 on 2025-11-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='Messages',
            field=models.JSONField(default=list),
        ),
    ]
